#!/bin/bash
if [ $# -ne 1 ]; then
    echo $0: usage: bsu name
    exit 1
fi
name=$1
name2="--reinstall"
name3="--uninstall"
name4="--run"
name5="--help"
if [[ $name == $name2 ]]; then
    if [ "$(id -u)" -ne 0 ]; then
	echo "Run this script as root" >&2
	exit 1
    fi
    rm -f /usr/local/bin/bsu /opt/BSU/bsu-install/bsu
    rm -rf /usr/local/bin/bsu > /dev/null
    rm -rf /opt/BSU > /dev/null
    rm -f ~/.local/share/applications/bsu.desktop > /dev/null
    rm -rf BSU > /dev/null
    whiptail --msgbox "Removal Complete" $(stty -a | tr \; \\012 |  grep -E 'rows|columns' | cut '-d ' -f3)
    git clone https://github.com/peanutbuttermurmite/BSU.git
    cd BSU/bsu-install
    chmod u+x bsu
    cd ..
    cd ..
    mv BSU /opt
    ln -s /opt/BSU/bsu-install/bsu /usr/local/bin/bsu
    cp -r bsu.desktop ~/.local/share
    whiptail --msgbox "BSU has been successfully reinstalled" $(stty -a | tr \; \\012 |
    grep -E 'rows|columns' | cut '-d ' -f3)
    exit 1
fi
if [[ $name == $name3 ]]; then
   if [ "$(id -u)" -ne 0 ]; then
	echo "Run this script as root" >&2
	exit 1
   fi
   rm -f /opt/BSU/bsu-install/bsu /usr/local/bin/bsu > /dev/null
   rm -rf /opt/BSU > /dev/null
   rm -f ~/.local/share/applications/bsu.desktop > /dev/null
   rm -rf BSU > /dev/null
   whiptail --msgbox "Uninstallation Complete" $(stty -a | tr \; \\012 |  grep -E 'rows|columns' | cut '-d ' -f3)
fi  
if [[ $name == $name4 ]]; then
   if [ "$(id -u)" -ne 0 ]; then
	echo "Run this script as root" >&2
	exit 1
   fi
   cd /opt/BSU
   python3 main.py
fi
if [[ $name == $name5 ]]; then
    whiptail --msgbox "Options:\n--reinstall:Reinstalls BSU\n--uninstall:Uninstall BSU\n--run:Runs BSU\n--help:Shows available commands" $(stty -a | tr \; \\012 |  grep -E 'rows|columns' | cut '-d ' -f3)
fi
