#!/bin/bash
if [ $# -ne 1 ]; then
    echo $0: usage: bsu name
    exit 1
fi
name=$1
name2="--reinstall"
name3="--uninstall"
name4="--run"
name5="--help"
if [[ $name == $name2 ]]; then
    if [ "$(id -u)" -ne 0 ]; then
	echo "run this script as root" >&2
	exit 1
    fi
    rm -rf /usr/local/bin/bsu > /dev/null
    rm -rf /opt/BSU > /dev/null
    rm -f ~/.local/share/applications/bsu.desktop > /dev/null
    rm -r BSU > /dev/null
    echo "Stage 1 of 2 complete"
    tput cup 1000 0 
    echo "-----"
    git clone https://github.com/peanutbuttermurmite/BSU.git > /dev/null
    mv BSU /opt
    ln -s /opt/BSU/bsu-install/bsu /usr/local/bin/bsu
    echo "Stage 2 of 2 complete"
    echo "BSU has been reinstalled successfully"
    exit 1
fi
if [[ $name == $name3 ]]; then
   if [ "$(id -u)" -ne 0 ]; then
	echo "run this script as root" >&2
	exit 1
   fi
   rm -rf /usr/local/bin/bsu > /dev/null
   rm -rf /opt/BSU > /dev/null
   rm -f ~/.local/share/applications/bsu.desktop > /dev/null
   rm -rf BSU > /dev/null
   echo "Removal Complete"
fi
if [[ $name == $name4 ]]; then
   if [ "$(id -u)" -ne 0 ]; then
	echo "run this script as root" >&2
	exit 1
   fi
   cd /opt/BSU
   python3 main.py
fi
if [[ $name == $name5 ]]; then 
    printf "Options:\n--reinstall:Reinstalls BSU\n--uninstall:Uninstall BSU\n--run:Runs BSU\n--help:Shows available commands"
fi
