import subprocess
import time
print("Loading...")
time.sleep(0.1)
print("10%")
time.sleep(1.1)
print("50%")
time.sleep(0.5)
print("90%")
time.sleep(0.1)
print("Loaded")
time.sleep(0.1)
subprocess.run(["gcc","main.c"], check=True)
tmp = subprocess.run(["./a.out"])  
print(tmp)
f = open("share")
contents = f.read()
f.close()
print(contents)